Javascript javascript1 week2
gsismandnm/hyf-homework pull request #7
Opened 2021-07-09 15:05 UTC by gsismandnm

Finished my homework.

2021-07-10 09:26 UTC, zuhairtaha requested changes

2021-07-10 09:26 UTC, zuhairtaha commented on javascript/javascript1/week2/candy-helper.js
> +}
Calculate the total spend inside `canBuyMoreCandy` function, not before it.

2021-07-10 09:26 UTC, zuhairtaha commented on javascript/javascript1/week2/flight-booking.js
> +    if (gender==="male" && formalName==="true"){
Use formalName as a boolean, not string type. So use `true`/`false` not `"true"` or `"false"`

2021-07-10 09:26 UTC, zuhairtaha commented on javascript/javascript1/week2/student-manager.js
> +    if (studentName === "") {
Use [trim](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim) to check long empty strings also like `"   "`

2021-07-10 09:26 UTC, zuhairtaha requested changes
Good job 
- I recommend you to use [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) extension to format your code. 
You can watch this [video](https://www.youtube.com/watch?v=iGWwmVmvFPk&ab_channel=SteveGriffith-Prof3ssorSt3v3) about it

2021-07-12 23:35 UTC, gsismandnm commented on javascript/javascript1/week2/student-manager.js
> +    if (studentName === "") {
Ok. I will change it..

2021-07-12 23:35 UTC, gsismandnm commented on javascript/javascript1/week2/candy-helper.js
> +}
Ok. I will do it.

2021-07-12 23:36 UTC, gsismandnm commented on javascript/javascript1/week2/flight-booking.js
> +    if (gender==="male" && formalName==="true"){
Ok. I will try to do it.

2021-07-21 18:04 UTC, merged